### ISSUE TITLE
What should I do if Iwant to use RX6950XT?

### ISSUE THREAD

**Issue by Km-wht** [kilinrax/gigabyte-z790-aero-g-efi#2]
What should I do if Iwant to use RX6950XT?

**Comment by kilinrax** [comment]
You’d need to fake a 6900XT I believe, same technique as faking the W6600 Pro into a 6600XT.  I can dig out the source for the respective codes later, if you can’t find one.

**Comment by kilinrax** [comment]
https://elitemacx86.com/threads/how-to-spoof-graphics-on-macos-intel-amd-nvidia.1008/
